
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  valkey:
    image: valkey/valkey:latest
    container_name: valkey_queue
    ports:
      - "6379:6379"
    command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - valkey_data:/data
    restart: always

volumes:
  postgres_data:
  valkey_data: